language: python
python:
  - 2.7
install: 
  - "pip install -r requirements.pip --use-mirrors"
  - "python setup.py install"
before_script:
  - "mysql -e 'create database TestcaseData;'"
  - "mysql -h 127.0.0.1 -u root TestcaseData < test_framework/core/testcaserepository.sql"
script: "cd test_framework/test/; nosetests -c tests.cfg"
after_script:
  - "mysql -e 'drop database TestcaseData;'"