language: python
python:
  - 2.7
install: "pip install -r requirements.pip --use-mirrors"
before_script:
  - python setup.py install 
  - mysql -e 'create database testcasedb;'
  - mysql -h 127.0.0.1 -u root testcasedb < test_framework/core/testcaserepository.sql
script: "cd test_framework/test/; nosetests -c tests.cfg"
after_script:
  - mysql -e 'drop database testcasedb;'